version: "3.6"

services:
  carting:
    build:
      context: ./SPPNautCarting
    env_file:
      - ./SPPNautCarting/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carting.rule=Host(`carting.sppnaut.shom.fr`)"

  spo:
    platform: linux/amd64
    build:
      context: ./SPPNautSPO
    env_file:
      - ./SPPNautSPO/PDFGenerator/http/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spo.rule=Host(`spo.sppnaut.shom.fr`)"

  proxy:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # Décommenter la ligne ci-dessous pour débugger traefik.
      # Les logs peuvent être visible avec la commande docker compose logs -f traefik
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # Le dashboard Traefik est accessible sur le port 8080, décommenter la ligne
      # ci-dessous et relancer avec docker compose up pour accéder à celui-ci.
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
